### ISSUE TITLE
JTAG2UPDI on Atmega32U4 (Arduino Leonardo, micro etc)

### ISSUE THREAD

**Issue by haweiler** [ElTangas/jtag2updi#22]
I have some ATtiny202 around to play with - and some 'micro pro' with 32U4 on. So I thought to use ElTangas jtag2updi to program those.

He gave me the tip to have a look at the ATmega4809 with SAMD11 used for USB. So it seemed just to be minor changes. I added those. After adding 'include Arduino.h' it compiled without errors, but doesn't seem to start after having done the transfer.
[jice.zip](https://github.com/ElTangas/jtag2updi/files/4007268/jice.zip)

**Comment by ElTangas** [comment]
Hello, as I mentioned on AVRFreaks, I recommend that you create a fork of jtag2updi to work on the Mega 32U4 port.

**Comment by haweiler** [comment]
Hello, I created a fork in jtag2updi, committed the 32U4 port there. Works using Linux right now due to an issue initializing the COM port using Windows.
